apiVersion: v1
kind: Service
metadata:
  name: backend-service-devops
  namespace: haproxy-controller-devops
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
