
services:
  vote:
    build: 
      context: ./vote
    ports:
      - "8080:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    depends_on:
      - db
  worker:
    build: 
      context: ./worker
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  db:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  result:
    build: 
      context: ./result
    ports:
      - "8081:4000"
    depends_on:
      - db

volumes:
  db-data:
