# red-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  initContainers:
  - name: init-myservice
    image: busybox
    command: ["sleep", "20"]
  containers:
  - name: redis
    image: redis
