# Use official Python Alpine image
FROM python:alpine

# Set working directory inside container
WORKDIR /app

# Copy the Python script into the container
COPY app.py .

# Run the script when the container starts
CMD ["python", "app.py"]
