apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-service
  namespace: haproxy-controller-devops
  labels:
    app: haproxy-ingress
spec:
  type: NodePort
  selector:
    app: haproxy-ingress
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32456
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
    nodePort: 32567
  - name: stat
    protocol: TCP
    port: 1024
    targetPort: 1024
    nodePort: 32678
