apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-deployment-devops
  namespace: haproxy-controller-devops
  labels:
    run:  ingress-default-backend
spec:
  template:
    metadata:
      name: backend-container-devops
      labels:
        run: ingress-default-backend
    spec:
      containers:
      - name: backend-container-devops
        image: gcr.io/google_containers/defaultbackend:1.0
        ports:
        - containerPort: 8080
  replicas: 1
  selector:
    matchLabels:
      run: ingress-default-backend