apiVersion: v1
kind: Service
metadata:
  name: ingress-service-devops
  namespace: haproxy-controller-devops
  labels:
    run: haproxy-ingress
spec:
  selector:
    run: haproxy-ingress
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32456
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
      nodePort: 32567
    - name: stat
      port: 1024
      protocol: TCP
      targetPort: 1024
      nodePort: 32678
