version: "3"
services:
  redis:
    image: redis:latest
    networks:
      - back-end
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - back-end

  voting:
    image: voting-app:latest
    ports:
      - 7070:80
    networks:
      - front-end
      - back-end

  result:
    image: result-app:latest
    ports:
      - 7071:80
    networks:
      - front-end
      - back-end

  worker:
    image: worker-app:latest
    networks:
      - back-end

networks:
  front-end:
  back-end: